<?php
//Fichier contenant tous les textes du site

$lang_site = array(

/******** Common *********/
	//Spécifiques à la langue
	'Lang' => 'en',
	'Changelang short' => 'fr',
	'Changelang long' => 'Français',

	//Header et footer
	'Skip link' => 'Go to content',
	'Footer content' => '%s ©'.date('Y').', All right reserved - All resources and tutorials published on this site belong to their respective authors | <a href="http://validator.w3.org/check?uri=referer">XHTML 1.0</a>',
	'Goto top' => 'Back to top',
	'Footer site' => 'Website',
	'Footer affiliates' => 'Affiliates',

	//Clés communes - En ordre alpha pour éviter les doublons
	'Actions' => 'Actions',
	'Add' => 'Add',
	'Add subcat' => 'Add subcat',
	'Add version' => 'Add version',
	'Admin' => 'Site Admin',
	'Advanced' => 'Advanced',
	'All' => 'All',
	'Approve' => 'Approve',
	'Archives' => 'Archives',
	'Ascending' => 'Ascending',
	'Author' => 'Author',
	'Author notes' => 'Author notes',
	'Autologin' => 'Auto login',
	'BBCode' => 'BBCode :',
	'By' => 'By',
	'by' => ' by ',
	'Categories' => 'Categories',
	'Category' => 'Category',
	'comments' => 'comments',
	'Comments' => 'Comments',
	'Comments moderation' => 'Comments moderation panel',
	'Comment preview' => 'Comment preview',
	'Delete' => 'Delete',
	'Descending' => 'Descending',
	'Description' => 'Description',
	'Download' => 'Download ',
	'Edit' => 'Edit',
	'English' => 'English',
	'Follow us' => 'Follow us',
	'Follow on' => 'Follow us on ',
	'Follow Facebook' => 'Follow us on Facebook',
	'Follow GooglePlus' => 'Follow us on Google+',
	'Follow Twitter' => 'Follow us on Twitter',
	'Forum' => 'Forum',
	'French' => 'Français',
	'General' => 'General',
	'Go back' => 'Back',
	'Google' => 'Advertisement',
	'Hack' => 'Hack',
	'Hacks' => 'Hacks',
	'Has versions' => 'Use versions ?',
	'Has versions info' => 'Useful for app tutorials (ex: Gimp)',
	'Home' => 'Home',
	'Info' => 'Informations',
	'Intermediate' => 'Intermediate',
	'img tag' => '[img] tag :',
	'Language' => 'Language',
	'Languages' => 'Languages',
	'Last posts' => 'Last posts',
	'Last posts by' => 'By',
	'Last update' => 'Last update',
	'Level' => 'Level',
	'Log in' => 'Log in',
	'Log out' => 'Log out',
	'Message' => 'Message',
	'My topics' => 'My topics',
	'Name' => 'Name',
	'Newbie' => 'Newbie',
	'News' => 'News',
	'Next' => 'Next',
	'No' => 'No',
	'off' => 'Disabled',
	'OK' => 'OK',
	'on' => 'Enabled',
	'Order' => 'Order',
	'Overview' => 'Overview',
	'Pages' => 'Pages',
	'Password' => 'Password',
	'PMs' => 'Messages',
	'Position' => 'Position',
	'Post comment' => 'Post comment',
	'Preview' => 'Preview of ',
	'Preview post' => 'Preview',
	'Preview style' => 'Style preview',
	'Previous' => 'Previous',
	'Profile' => 'My profile',
	'Published' => 'Posted on ',
	'Quote' => 'Quote',
	'Read tutorial' => 'Read tutorial',
	'Register' => 'Register',
	'Resource' => 'Resource',
	'Resources' => 'Resources',
	'Save changes' => 'Save changes',
	'Screenshot' => 'Screenshot',
	'Screenshots' => 'Screenshots',
	'Set as default' => 'Set as default',
	'Settings' => 'Settings',
	'Show all' => 'Show all',
	'Smilies' => 'Smilies :',
	'Sort' => 'Sort',
	'Sort by' => 'Sort by',
	'Sort tutorials' => 'Sort tutorials',
	'Styles' => 'Styles',
	'Style' => 'Style',
	'Subcategories' => 'Subcategory',
	'Submit' => 'Submit',
	'Summary' => 'Summary',
	'Tutorial' => 'Tutorial',
	'Tutorials' => 'Tutorials',
	'Tutorial icon' => 'Tutorial icon',
	'Tutorial ID' => 'Tutorial ID',
	'Type' => 'Type',
	'Types' => 'Types',
	'Unapprove' => 'Unapprove',
	'Update positions' => 'Update positions',
	'Updated' => 'Updated on ',
	'URL' => 'URL',
	'Use right click' => 'Use right-click to grab link URL.',
	'Versions' => 'Versions',
	'Username' => 'Username',
	'Version' => 'Version',
	'View details' => 'View details',
	'View info' => 'View info',
	'View list' => 'View list of ',
	'View tutorials' => 'View tutorials',
	'wrote' => 'wrote',
	'Yes' => 'Yes',

	//Redirection
	'Redirecting' => 'Redirecting',
	'Click redirect' => 'Click here if you don’t want to wait (or if your browser doesn’t redirect you automatically).',

	//Pour la page d'accueil v6
	'About site' => ' is…',
	'Latest news' => 'Latest news',
	'Latest tutorials' => 'Latest tutorials',
	'Latest resources' => 'Latest resources',

	//Spécifique aux commentaires
	'Add comment' => 'Add a comment',
	'Edit comment' => 'Edit a comment',
	'Delete comment' => 'Delete a comment',
	'Delete comment head' => 'Delete a comment',
	'Confirm delete comment subhead' => 'Confirm deletion of this comment',
	'Confirm delete comment info' => 'Do you really want to delete this following comment ?<br /><q>%s</q>',
	'Delete comment warn' => '<strong>WARNING !</strong> The deletion cannot be undone !',
	'Comment errors' => 'Errors in this comment',
	'Comment errors info' => 'The following errors must be fixed befort sending this comment :',
	'Comment preview' => 'Preview comment',
	'Comment added redirect' => 'Comment added. Redirecting …',
	'Comment edited redirect' => 'Comment edited. Redirecting …',
	'Comment deleted redirect' => 'Comment deleted. Rediracting …',

	//Administration - Général
	'Admin heading' => 'Site Admin',
	'Admin manage settings' => 'General settings',
	'Admin manage pages' => 'Manage pages',
	'Admin manage res' => 'Manage resources',
	'Admin manage tuts' => 'Manage tutorials',
	'Admin stats' => 'Site stats',
	'Admin nb res' => 'Nb of resources',
	'Admin nb tutorials' => 'Nb of tutorials',
	'Admin nb comments' => 'Nb of comments',
	'Admin nb pages' => 'Nb of pages',

	//Config générale
	'Admin general settings' => 'General options',
	'Admin cfg site desc' => 'Site description',
	'Admin intro module settings' => 'Intro module options',
	'Admin cfg enable intro' => 'Enable intro module',
	'Admin cfg site intro' => 'Intro content',
	'Admin news module settings' => 'News module options',
	'Admin cfg enable news' => 'Enable news module',
	'Admin cfg forum news' => 'News forum',
	'Admin cfg nb news home' => 'Nb of news to display on homepage',
	'Admin cfg nb news page' => 'Nb of news to display on news page',
	'Admin resources module settings' => 'Resources module options',
	'Admin cfg enable res' => 'Enable resources module',
	'Admin cfg nb res home' => 'Nb of resources to display on homepage',
	'Admin cfg styles per page' => 'Styles per page',
	'Multiple 2' => 'Must be a multiple of 2',
	'Admin cfg hacks per page' => 'Hacks per page',
	'Multiple 3' => 'Must be a multiple of 3',
	'Admin tutorials module settings' => 'Tutorials module options',
	'Admin cfg enable tuts' => 'Enable tutorials module',
	'Admin cfg nb tuts home' => 'Nb of tutorials to display on homepage',
	'Admin cfg tuts per page' => 'Tutorials per page',
	'Admin sidebar modules settings' => 'Sidebar options',
	'Admin cfg enable lastposts' => 'Enable last posts module',
	'Admin cfg nb lastposts' => 'Nb of last replies to display',
	'Admin cfg enable ads' => 'Enable advertisement module',
	'Admin cfg your ads' => 'Your advertisement',
	'Admin cfg enable social' => 'Enable social links module',
	'Admin cfg social links' => 'Social links',
	'Admin footer settings' => 'Footer options',
	'Admin cfg enable footer links' => 'Enable footer links',
	'Admin cfg footer sitelinks' => 'Website links',
	'Admin cfg footer affiliates' => 'Affiliate links',

	'Options updated redirect' => 'Options updated. Redirecting …',

	//Administrations - Catégories
	'Admin add cat' => 'Add a category',
	'Admin add subcat' => 'Add a subcategory',
	'Admin add version' => 'Add a version',
	'Admin edit cat' => 'Edit a category',
	'Admin edit subcat' => 'Edit a subcategory',
	'Admin edit version' => 'Edit a version',
	'Admin delete category' => 'Delete a category',
	'Admin delete subcat' => 'Delete a subcategory',
	'Admin delete version' => 'Delete a version',

	'Admin cat name' => 'Category name',
	'Admin sub name' => 'Subcategory name',
	'Admin ver name' => 'Version name',
	'Admin cat clear' => 'Category short name',
	'Admin sub clear' => 'Subcategory short name',
	'Admin cat desc' => 'Category description',
	'Admin sub desc' => 'Subcategory description',
	'Admin cat icon' => 'Category icon',

	'Admin cat added redirect' => 'Category added. Redirecting …',
	'Admin subcat added redirect' => 'Subcategory added. Redirecting …',
	'Admin version added redirect' => 'Version added. Redirecting …',
	'Admin cat edited redirect' => 'Category edited. Redirecting …',
	'Admin subcat edited redirect' => 'Subcategory edited. Redirecting …',
	'Admin version edited redirect' => 'Version edited. Redirecting …',
	'Admin cat deleted redirect' => 'Category deleted. Redirecting …',
	'Admin subcat deleted redirect' => 'Subcategory deleted. Redirecting …',
	'Admin version deleted redirect' => 'Version deleted. Redirecting …',

	'Admin delete res cat head' => 'Delete a category (and its content)',
	'Admin delete res subcat head' => 'Delete a subcategory (and its content)',
	'Admin delete tut cat head' => 'Delete a category (and its content)',
	'Admin delete version head' => 'Delete a version (and its content)',
	'Admin confirm delete cat subhead' => 'Confirm deletion of this category',
	'Admin confirm delete subcat subhead' => 'Confirm deletion of this subcategory',
	'Admin confirm delete version subhead' => 'Confirm deletion of this version',
	'Admin confirm delete cat info' => 'Do you really want to delete the following category ?<br /><q>%s</q>',
	'Admin confirm delete subcat info' => 'Do you really want to delete the following subcategory ?<br />%s</q>',
	'Admin confirm delete version info' => 'Do you really want to delete the following version ?<br /><q>%s</q>',
	'Admin delete res cat warn' => '<strong>WARNING !</strong> Deleting a category will also delete all subcategories and tutorials it contains !',
	'Admin delete res subcat warn' => '<strong>WARNING !</strong> Deleting a subcategory will also delete all resources it contains !',
	'Admin delete tut cat warn' => '<strong>WARNING !</strong> Deleting a category will also delete all tutorials and versions it contains !',
	'Admin delete version warn' => '<strong>WARNING !</strong> Deleting a version will also delete all tutorials it contains !',

	//Administration - Ressources
	'Admin add res' => 'Add resource',
	'Admin edit res' => 'Update resource',
	'Admin delete res' => 'Delete resource',

	'Admin res name' => 'Resource name',
	'Admin res shortdesc' => 'Short description',
	'Admin res desc' => 'Long description',
	'Admin res notes' => 'Author notes',

	'Admin res added redirect' => 'Resource added. Redirecting …',
	'Admin res edited redirect' => 'Resource updated. Redirecting …',
	'Admin res approved redirect' => 'Resource approved. Redirecting …',
	'Admin res unapproved redirect' => 'Resource unapproved. Redirecting …',
	'Admin res deleted redirect' => 'Resource deleted. Redirecting …',

	'Admin delete res head' => 'Delete a resource (and its screenshots)',
	'Admin confirm delete res subhead' => 'Confirm deletion of this resource',
	'Admin confirm delete res info' => 'Do you really want to delete the following resource ?<br /><q>%s</q>',
	'Admin delete res warn' => '<strong>WARNING !</strong> Deleting a resource will also delete all screenshots associated to it !',

	//Administration - captures d'écran
	'Admin add screen' => 'Add a screenshot',
	'Admin edit screen' => 'Update a screenshot',
	'Admin delete screen' => 'Delete a screenshot',

	'Admin legend english' => 'Legend in English',
	'Admin legend french' => 'Legend in French',
	'Admin download link' => 'Download link',
	'Admin resource screenshots' => 'Screenshot',

	'Admin screenshot added redirect' => 'Screenshot added. Redirecting …',
	'Admin screenshot updated redirect' => 'Screenshot updated. Redirecting …',
	'Admin screenshot deleted redirect' => 'Screenshot deleted. Redirecting …',
	'Admin default screen changed redirect' => 'Default screenshot changed. Redirecting …',

	'Admin delete screen head' => 'Delete a screenshot',
	'Admin confirm delete screen subhead' => 'Confirm deletion of this screenshot',
	'Admin confirm delete screen info' => 'Do you really want to delete the following screenshot ?<br /><q>%s</q>',
	'Admin delete screen warn' => '<strong>WARNING !</strong> The deletion cannot be undone !',

	//Administration - Types de tutoriels
	'Admin add type' => 'Add a tutorial type',
	'Admin edit type' => 'Edit a tutorial type',
	'Admin delete type' => 'Delete a tutorial type',

	'Admin type name' => 'Tutorial type name',

	'Admin type added redirect' => 'Tutorial type added. Redirecting …',
	'Admin type edited redirect' => 'Tutorial type edited. Redirecting …',
	'Admin type deleted redirect' => 'Tutorial type deleted. Redirecting …',

	'Admin delete type head' => 'Delete a tutorial type',
	'Admin confirm delete type subhead' => 'Confirm deletion of this tutorial type',
	'Admin confirm delete type info' => 'Do you really want to delete the following tutorial type ?<br /><q>%s</q>',
	'Admin delete type warn' => '<strong>WARNING !</strong> All tutorial using this type won’t have any defined type and you will have to edit them to assign a new type !',

	//Administrations - Tutoriels
	'Admin add tut' => 'Add a tutorial',
	'Admin edit tut' => 'Edit a tutorial',
	'Admin delete tut' => 'Delete a tutorial',

	'Admin tut name' => 'Tutorial name',
	'Admin tut desc' => 'Tutorial description',
//	'Admin tut extra' => 'Informations supplémentaires',
	'Admin tut icon' => 'Tutorial icon',
	'Admin tut type' => 'Tutorial type',
	'Admin tut level' => 'Difficulty level',

	'Admin tut added redirect' => 'Tutorial added. Redirecting …',
	'Admin tut edited redirect' => 'Tutoriel edited. Redirecting …',
	'Admin tut deleted redirect' => 'Tutoriel deleted. Redirecting …',

	'Admin delete tut head' => 'Delete a tutorial (and its parts)',
	'Admin confirm delete tut subhead' => 'Confirm deletion of this tutorial',
	'Admin confirm delete tut info' => 'Do you really want to delete the following tutorial ?<br /><q>%s</q>',
	'Admin delete tut warn' => '<strong>WARNING !</strong> Deleting a tutorial will also delete the parts associated to it !',

	'Admin add part' => 'Add a part',
	'Admin edit part' => 'Edit a part',
	'Admin delete part' => 'Delete a part',

	'Admin part name' => 'Part name',
	'Admin part text' => 'Part text',

	'Admin part added redirect' => 'Part added. Redirecting …',
	'Admin part edited redirect' => 'Part edited. Redirecting …',
	'Admin part deleted redirect' => 'Part deleted. Redirecting …',

	'Admin delete tut part head' => 'Delete a tutorial part',
	'Admin confirm delete tut part subhead' => 'Confirm deletion of this tutorial part',
	'Admin confirm delete tut part info' => 'Do you really want to delete the following tutorial part ?<br /><q>%s</q>',
	'Admin delete tut part warn' => '<strong>WARNING !</strong> This operation cannot be undone !',

	//Administration - Pages
	'Admin add page' => 'Add a static page',
	'Admin edit page' => 'Edit a static page',
	'Admin delete page' => 'Delete a static page',

	'Admin page title' => 'Page title',
	'Admin page clean title' => 'Page short title',
	'Admin page text' => 'Page text (BBCode allowed)',

	'Admin page added redirect' => 'Page added. Redirecting …',
	'Admin page edited redirect' => 'Page edited. Redirecting …',
	'Admin page deleted redirect' => 'Page deleted. Redirecting …',

	'Admin delete page head' => 'Delete a static page',
	'Admin confirm delete page subhead' => 'Confirm deletion of this static page',
	'Admin confirm delete page info' => 'Do you really want to delete the following page ?<br /><q>%s</q>',
	'Admin delete page warn' => '<strong>WARNING !</strong> This operation cannot be undone !',

	//Erreurs - Public/commun
	'No news' => 'No news',
	'No tutorial' => 'No tutorial',
	'No style' => 'No style',
	'No screen' => 'No screenshot',
	'No cat' => 'No category',
	'No subcat' => 'No subcategory',
	'No resource' => 'No resource',
	'No comment' => 'No comment',
	'No part' => 'No part',
	'No type' => 'No type',
	'No page' => 'No page',

	'Category not found' => 'The category you are looking for doesn’t exist !',
	'Subcat not found' => 'The subcategory you are looking for doesn’t exist !',
	'part not found' => 'The part you are looking for doesn’t exist !',
	'Comment not found' => 'The comment you are looking for doesn’t exist !',
	'Resource not found' => 'The resource you are looking for doesn’t exist or is not validated !',
	'Tutorial not found' => 'The tutorial you are looking for doesn’t exist or is not validated !',
	'Page not found' => 'The page you are looking for doesn’t exist !',
	'Wrong format' => 'The format is incorrect ! Please read the doc page in order to know how to properly format data',

	'No screenshot sent'	=> 'No screenshot was sent !',
	'Cannot edit comment' => 'Sorry but you don’t have the required permissions to edit this comment !',
	'All caps message' => 'It isn’t allowed to write a whole message in capitals.',
	'No message after censoring' => 'You must enter a message. After censoring, your message is empty.',
	'Must login to comment' => 'You must log in to write a comment.',

	'Bad request' => 'Bad request. The link you followed is incorrect or outdated.',
	'No view' => 'You do not have permission to view this page.',
	'No permission'	=> 'You do not have permission to access this page.',
	'Bad referrer' => 'Bad HTTP_REFERER. You were referred to this page from an unauthorized source. If the problem persists please make sure that \'Base URL\' is correctly set in Admin/Options and that you are visiting the forum by navigating to that URL. More information regarding the referrer check can be found in the FluxBB documentation.',

	//Erreurs - Admin
	'Admin no catname' => 'The category name is empty',
	'Admin no catclear' => 'The category short name is empty',
	'Admin no data' => 'No data was sent. Make sure you selected the languages to use and to fill in the corresponding fields.',
	'Admin no pic' => 'No pic was sent or the pic wasn’t correctly sent.',
	'Admin no subname' => 'The subcategory name is empty',
	'Admin no subclear' => 'The subcategory short name is empty',
	'Admin no desc' => 'The description is empty',
	'Admin no type' => 'No type was defined',
	'Admin no file' => 'No file !',
	'Admin no folder' => 'The following folder doesn’t exist : %s',
	'Admin no resname' => 'The resource name is empty',
	'Admin no shortdesc' => 'The short description is empty',
	'Admin no longdesc' => 'The long description is empty',
	'Admin no notes' => 'The author notes are empty',
	'Admin no typename' => 'At least one of the two tutorial type name field is empty !',
//	'Admin no typecat' => 'Vous n’avez spécifié aucune catégorie pour le type de tutoriel !',
	'Admin no tutname' => 'The tutorial name is empty !',
	'Admin no part name' => 'The part name is empty !',
	'Admin no text' => 'The part text is empty !',
	'Admin no language' => 'No language was selected !',
	'Admin no page title' => 'The page title is empty !',
	'Admin no clean title' => 'The page short title is empty !',

	'Admin must have categories' => 'You must have created at least one category before using this page !',
	'Admin must be integer'	=>	'The position must be a positive integer.',
	'Admin bad transfer' => 'An error occurred while transferring the pic',
	'Admin file too big' => 'The file is too big !',
	'Admin bad extension' => 'Wrong extension !',
	'Admin transfer success' => 'The file was successfully transferred !',
	'Admin bad chmod' => 'The requested directory doesn’t have write permission ! Its CHMOD must be set to 777.',
	'Admin upload failed' => 'The upload has failed, at least one criteria wasn’t filled :',
	'Admin error while uploading' => 'Please fix the following errors before trying uploading :',

	//Bouts de titres spécifiques aux pages v6
	'Pagename home' => 'Home',
	'Pagename news' => 'News',
	'Pagename res for' => 'Resources for ',
	'Pagename res home' => 'Resources homepage',
	'Pagename for' => ' for ',
	'Pagename tut home' => 'Tutorials homepage',
	'Pagename view tutorial' => 'Read tutorial',
	'Pagename view comments' => 'View comments',
	'Pagename write comment' => 'Write/Edit a comment',
	'Pagename adm home' => 'Administration home',
	'Pagename adm cfg' => 'Site settings',
	'Pagename adm resources' => 'Resources admin',
	'Pagename adm res cat' => 'Resource categories admin',
	'Pagename adm add res' => 'Add a resource',
	'Pagename adm tutorials' => 'Tutorials admin',
	'Pagename adm tuts cat' => 'Tutorial categories admin',
	'Pagename adm tuts types' => 'Tutorial type admin',
	'Pagename adm pages' => 'Static pages admin',
	'Pagename adm comments' => 'Comments admin',

	//titres d'accueil
	'Title home' => 'Welcome on %s !',
	'Title news' => 'Latest news !',
	'Title resources' => 'Resources for your sites',
	'Title tutorials' => 'Tutorials for your sites and apps',
	'Explain home' => '<p>Tutorials and resources for your sites, with the free software spirit !</p>',
	'Explain news' => '<p>Website news !</p>',
	'Explain res home' => '<p>Here you will find styles, hacks (modifications, addons and snippets) and other resources to customize your sites and forums.</p>',
	'Explain tuts home' => '<p>Here you will find tutorials and tips to help you to customize your sites and forums.</p>',
	'Title adm home' => 'Administration home',
	'Explain adm home' => '<p>Here you can manage resources, tutorials, comments and pages published by you or your members, as well as configure your site.</p>',
	'Title adm cfg' => 'Site settings',
	'Explain adm cfg' => '<p>Here you can configure the modules of your site.  Take note that a special markup system is used to ensure a flexible management of multilanguages.  To learn more about how it works, consult the wiki page about this system on the site’s GitHub repository.</p>',
	'Title adm resources' => 'Resources admin',
	'Explain adm res home' => '<p>Here you can manage everything that is related to resources.</p>',
	'Title adm res cat' => 'Resource categories Admin',
	'Explain adm res cat' => '<p>Here you can add, edit, delete and organize your categories and subcategories for the resources that will be published on this site.</p><p>The categories must represent the platform or CMS that correspond to the resources while the subcategories allow to divide the resources into two types within the category, wether it’s a modification (hack) or a style.</p>',
	'Explain adm resources' => '<p>Here you can add, update and delete resources and its associated screenshots.</p>',
	'Title adm tutorials' => 'Tutorials admin',
	'Explain adm tuts home' => '<p>Here you can manage everything that is related to tutorials.</p>',
	'Explain adm tutorials' => '<p>Here you can add, edit and delete tutorials and its parts.</p>',
	'Title adm tuts cat' => 'Tutorial categories admin',
	'Explain adm tuts cat' => '<p>Here you can add, edit, delete and organize your categories for tutorials that will be published on this site.</p><p>The categories must represent the platform or CMS that correspond to the tutorials, while versions allow to specify the version of the app or CMS for which the tutorial applies.</p>',
	'Title adm tuts types' => 'Tutorial types admin',
	'Explain adm tuts types' => '<p>Here you can manage tutorial types, in order to sort them to facilitate searching for users.  For example, for Gimp tutorials, we can add types such as « Design », « Touch up », « Tip » and so on.  Some types such as « Tips » can be used by more than one category.</p>',
	'Explain add comment' => '<p>Comments are made to express your opinion about the tutorial.  If some points need to be improved, please be constructive in your critique, by detailing the point that need to be improved.<br />IMPORTANT : Comments must not be used for support requests, this must be done on the forum !</p>',
	'Title adm pages' => 'Static pages admin',
	'Explain adm pages' => '<p>Here you can add, edit and delete static pages in order to show infos that aren’t meant to change frequently.  BBCodes are allowed.</p>',
	'Title adm comments' => 'Comments admin',
	'Explain adm comments' => '<p>Here you can moderate comments whatever the tutorial that it’s related.  You can use the drop-down menu to show only comments from a specific tutorial.</p>'
);
