<?php
//Fichier contenant tous les textes du site

$lang_site = array(

/******** Common *********/
	//Spécifiques à la langue
	'Lang' => 'fr',
	'Changelang short' => 'en',
	'Changelang long' => 'English',

	//Header et footer
	'Skip link' => 'Aller au contenu',
	'Footer content' => '%s ©'.date('Y').', tous droits réservés - Les ressources et tutoriels publiés sur ce site sont la propriété de leurs auteurs respectifs | <a href="http://validator.w3.org/check?uri=referer">XHTML 1.0</a>',
	'Goto top' => 'Revenir en haut',
	'Footer site' => 'Le site',
	'Footer affiliates' => 'Partenaires',

	//Clés communes - En ordre alpha pour éviter les doublons
	'Actions' => 'Actions',
	'Add' => 'Ajouter',
	'Add subcat' => 'Ajouter une sous-catégorie',
	'Add version' => 'Ajouter une version',
	'Admin' => 'Administration',
	'Advanced' => 'Avancé',
	'All' => 'Tous',
	'Approve' => 'Approuver',
	'Archives' => 'Archives',
	'Ascending' => 'Ascendant',
	'Author' => 'Auteur',
	'Author notes' => 'Notes de l’auteur',
	'Autologin' => 'Connexion auto',
	'BBCode' => 'BBCode :',
	'By' => 'Par',
	'by' => ' par ',
	'Categories' => 'Catégories',
	'Category' => 'Catégorie',
	'comments' => 'commentaires',
	'Comments' => 'Commentaires',
	'Comments moderation' => 'Panneau de modération des commentaires',
	'Comment preview' => 'Aperçu du commentaire',
	'Delete' => 'Supprimer',
	'Descending' => 'Descendant',
	'Description' => 'Description',
	'Download' => 'Télécharger le ',
	'Edit' => 'Modifier',
	'English' => 'English',
	'Follow us' => 'Nous suivre',
	'Follow on' => 'Nous suivre sur ',
	'Follow Facebook' => 'Nous suivre sur Facebook',
	'Follow GooglePlus' => 'Nous suivre sur Google+',
	'Follow Twitter' => 'Nous suivre sur Twitter',
	'Forum' => 'Forum',
	'French' => 'Français',
	'General' => 'Général',
	'Go back' => 'Retour',
	'Google' => 'Publicité',
	'Hack' => 'Hack',
	'Hacks' => 'Hacks',
	'Has versions' => 'Utiliser les versions',
	'Has versions info' => 'Utile pour les tutoriels de logiciels (ex: Gimp)',
	'Home' => 'Accueil',
	'Info' => 'Informations',
	'Intermediate' => 'Intermédiaire',
	'img tag' => 'Balise [img] :',
	'Language' => 'Langue',
	'Languages' => 'Langues',
	'Last posts' => 'Derniers messages',
	'Last posts by' => 'Par',
	'Last update' => 'Dernière MAJ',
	'Level' => 'Niveau',
	'Log in' => 'Connexion',
	'Log out' => 'Déconnexion',
	'Message' => 'Message',
	'My topics' => 'Mes interventions',
	'Name' => 'Nom',
	'Newbie' => 'Débutant',
	'News' => 'News',
	'Next' => 'Suivant',
	'No' => 'Non',
	'off' => 'Désactivé',
	'OK' => 'OK',
	'on' => 'Activé',
	'Order' => 'Ordre',
	'Overview' => 'Aperçu',
	'Pages' => 'Pages',
	'Password' => 'Mot de passe',
	'PMs' => 'Messagerie',
	'Position' => 'Position',
	'Post comment' => 'Publier un commentaire',
	'Preview' => 'Aperçu du ',
	'Preview post' => 'Prévisualiser',
	'Preview style' => 'Aperçu du style',
	'Previous' => 'Précédent',
	'Profile' => 'Mon profil',
	'Published' => 'Publié le ',
	'Quote' => 'Citer',
	'Read tutorial' => 'Lire le tutoriel',
	'Register' => 'S’enregistrer',
	'Resource' => 'Ressource',
	'Resources' => 'Ressources',
	'Save changes' => 'Enregistrer',
	'Screenshot' => 'Capture d’écran',
	'Screenshots' => 'Captures d’écran',
	'Set as default' => 'Par défaut',
	'Settings' => 'Configuration',
	'Show all' => 'Tout afficher',
	'Smilies' => 'Émoticônes :',
	'Sort' => 'Trier',
	'Sort by' => 'Trier par',
	'Sort tutorials' => 'Trier les tutoriels',
	'Styles' => 'Styles',
	'Style' => 'Style',
	'Subcategories' => 'Sous-catégorie',
	'Submit' => 'Envoyer',
	'Summary' => 'Sommaire',
	'Tutorial' => 'Tutoriel',
	'Tutorials' => 'Tutoriels',
	'Tutorial icon' => 'Icone du tutoriel',
	'Tutorial ID' => 'ID du tuto',
	'Type' => 'Type',
	'Types' => 'Types',
	'Unapprove' => 'Désapprouver',
	'Update positions' => 'Modifier les positions',
	'Updated' => 'Modifié le ',
	'URL' => 'URL',
	'Use right click' => 'Utilisez le clic-droit pour récupérer l’adresse du lien.',
	'Versions' => 'Versions',
	'Username' => 'Nom d’utilisateur',
	'Version' => 'Version',
	'View details' => 'Voir les détails',
	'View info' => 'Voir les informations',
	'View list' => 'Voir la liste des ',
	'View tutorials' => 'Voir les tutoriels',
	'wrote' => 'a écrit',
	'Yes' => 'Oui',

	//Redirection
	'Redirecting' => 'Redirection',
	'Click redirect' => 'Cliquez ici si vous ne voulez pas attendre (ou si votre navigateur ne vous redirige pas automatiquement).',

	//Pour la page d'accueil v6
	'About site' => ' c’est…',
	'Latest news' => 'Dernières news',
	'Latest tutorials' => 'Derniers tutoriels',
	'Latest resources' => 'Dernières ressources',

	//Spécifique aux commentaires
	'Add comment' => 'Ajouter un commentaire',
	'Edit comment' => 'Modifier un commentaire',
	'Delete comment' => 'Supprimer un commentaire',
	'Delete comment head' => 'Supprimer le commentaire',
	'Confirm delete comment subhead' => 'Confirmer la suppression du commentaire',
	'Confirm delete comment info' => 'Souhaitez-vous vraiment supprimer le commentaire suivant ?<br /><q>%s</q>',
	'Delete comment warn' => '<strong>ATTENTION !</strong> La suppression sera irréversible !',
	'Comment errors' => 'Erreurs dans le commentaire',
	'Comment errors info' => 'Les erreurs suivantes doivent être corrigées pour que le commentaire puisse être envoyé :',
	'Comment preview' => 'Prévisualisation du commentaire',
	'Comment added redirect' => 'Commentaire ajouté. Redirection …',
	'Comment edited redirect' => 'Commentaire édité. Redirection …',
	'Comment deleted redirect' => 'Commentaire supprimé. Rediraction …',

	//Administration - Général
	'Admin heading' => 'Administration du site',
	'Admin manage settings' => 'Configuration générale',
	'Admin manage pages' => 'Gérer les pages',
	'Admin manage res' => 'Gérer les ressources',
	'Admin manage tuts' => 'Gérer les tutoriels',
	'Admin stats' => 'Statistiques du site',
	'Admin nb res' => 'Nombre de ressources',
	'Admin nb tutorials' => 'Nombre de tutoriels',
	'Admin nb comments' => 'Nombre de commentaires',
	'Admin nb pages' => 'Nombre de pages',

	//Config générale
	'Admin general settings' => 'Options générales',
	'Admin cfg site desc' => 'Description du site',
	'Admin intro module settings' => 'Options du module de présentation',
	'Admin cfg enable intro' => 'Activer le module de présentation',
	'Admin cfg site intro' => 'Contenu de la présentation',
	'Admin news module settings' => 'Options du module de news',
	'Admin cfg enable news' => 'Activer le module de news',
	'Admin cfg forum news' => 'Forum des news',
	'Admin cfg nb news home' => 'Nombre de news à afficher sur l’accueil',
	'Admin cfg nb news page' => 'Nombre de news à afficher sur la page des news',
	'Admin resources module settings' => 'Options du module des ressources',
	'Admin cfg enable res' => 'Activer le module des ressources',
	'Admin cfg nb res home' => 'Nombre de ressources à afficher sur l’accueil',
	'Admin cfg styles per page' => 'Styles par page',
	'Multiple 2' => 'Doit être un multiple de 2',
	'Admin cfg hacks per page' => 'Hacks par page',
	'Multiple 3' => 'Doit être un multiple de 3',
	'Admin tutorials module settings' => 'Options du module des tutorials',
	'Admin cfg enable tuts' => 'Activer le module des tutoriels',
	'Admin cfg nb tuts home' => 'Nombre de tutoriels à afficher sur l’accueil',
	'Admin cfg tuts per page' => 'Tutoriels par page',
	'Admin sidebar modules settings' => 'Options de la sidebar',
	'Admin cfg enable lastposts' => 'Activer le module des dernières réponses',
	'Admin cfg nb lastposts' => 'Nombre de réponses à afficher',
	'Admin cfg enable ads' => 'Activer le module des publicités',
	'Admin cfg your ads' => 'Votre publicité',
	'Admin cfg enable social' => 'Activer le module des liens sociaux',
	'Admin cfg social links' => 'Liens sociaux',
	'Admin footer settings' => 'Options du footer',
	'Admin cfg enable footer links' => 'Activer les liens du footer',
	'Admin cfg footer sitelinks' => 'Liens du site',
	'Admin cfg footer affiliates' => 'Liens de partenariats',

	'Options updated redirect' => 'Options mises à jour. Redirection …',

	//Administrations - Catégories
	'Admin add cat' => 'Ajouter une catégorie',
	'Admin add subcat' => 'Ajouter une sous-catégorie',
	'Admin add version' => 'Ajouter une version',
	'Admin edit cat' => 'Modifier une catégorie',
	'Admin edit subcat' => 'Modifier une sous-catégorie',
	'Admin edit version' => 'Modifier une version',
	'Admin delete category' => 'Supprimer une catégorie',
	'Admin delete subcat' => 'Supprimer une sous-catégorie',
	'Admin delete version' => 'Supprimer une version',

	'Admin cat name' => 'Nom de la catégorie',
	'Admin sub name' => 'Nom de la sous-catégorie',
	'Admin ver name' => 'Nom de le version',
	'Admin cat clear' => 'Non court de la catégorie',
	'Admin sub clear' => 'Nom court de la sous-catégorie',
	'Admin cat desc' => 'Description de la catégorie',
	'Admin sub desc' => 'Description de la sous-catégorie',
	'Admin cat icon' => 'Icône de la catégorie',

	'Admin cat added redirect' => 'Catégorie ajoutée. Redirection …',
	'Admin subcat added redirect' => 'Sous-catégorie ajoutée. Redirection …',
	'Admin version added redirect' => 'Version ajoutée. Redirection …',
	'Admin cat edited redirect' => 'Catégorie modifiée. Redirection …',
	'Admin subcat edited redirect' => 'Sous-catégorie modifiée. Redirection …',
	'Admin version edited redirect' => 'Version modifiée. Redirection …',
	'Admin cat deleted redirect' => 'Catégorie supprimée. Redirection …',
	'Admin subcat deleted redirect' => 'Sous-catégorie supprimée. Redirection …',
	'Admin version deleted redirect' => 'Version supprimée. Redirection …',

	'Admin delete res cat head' => 'Supprimer la catégorie (et son contenu)',
	'Admin delete res subcat head' => 'Supprimer la sous-catégorie (et son contenu)',
	'Admin delete tut cat head' => 'Supprimer la catégorie (et son contenu)',
	'Admin delete version head' => 'Supprimer la version (et son contenu)',
	'Admin confirm delete cat subhead' => 'Confirmer la suppression de la catégorie',
	'Admin confirm delete subcat subhead' => 'Confirmer la suppression de la sous-catégorie',
	'Admin confirm delete version subhead' => 'Confirmer la suppression de la version',
	'Admin confirm delete cat info' => 'Souhaitez-vous vraiment supprimer la catégorie suivantes ?<br /><q>%s</q>',
	'Admin confirm delete subcat info' => 'Souhaitez-vous vraiment supprimer la sous-catégorie suivante ?<br /><q>%s</q>',
	'Admin confirm delete version info' => 'Souhaitez-vous vraiment supprimer la version suivante ?<br /><q>%s</q>',
	'Admin delete res cat warn' => '<strong>ATTENTION !</strong> Supprimer une catégorie entraîne la suppression des sous-catégories et ressources qu’elle contient !',
	'Admin delete res subcat warn' => '<strong>ATTENTION !</strong> Supprimer une sous-catégorie entraîne la suppression des ressources qu’elle contient !',
	'Admin delete tut cat warn' => '<strong>ATTENTION !</strong> Supprimer une catégorie entraîne la suppression des tutoriels et versions qu’elle contient !',
	'Admin delete version warn' => '<strong>ATTENTION !</strong> Supprimer une version entraîne la suppression des tutoriels qu’elle contient !',

	//Administration - Ressources
	'Admin add res' => 'Ajouter une ressource',
	'Admin edit res' => 'Mettre à jour une ressource',
	'Admin delete res' => 'Supprimer une ressource',

	'Admin res name' => 'Nom de la ressource',
	'Admin res shortdesc' => 'Courte description',
	'Admin res desc' => 'Description longue',
	'Admin res notes' => 'Notes de l’auteur',

	'Admin res added redirect' => 'Ressource ajoutée. Redirection …',
	'Admin res edited redirect' => 'Ressource mise à jour. Redirection …',
	'Admin res approved redirect' => 'Ressource approuvée. Redirection …',
	'Admin res unapproved redirect' => 'Ressource désapprouvée. Redirection …',
	'Admin res deleted redirect' => 'Ressource supprimée. Redirection …',

	'Admin delete res head' => 'Supprimer la ressource (et ses captures d’écran)',
	'Admin confirm delete res subhead' => 'Confirmer la suppression de la ressource',
	'Admin confirm delete res info' => 'Souhaitez-vous vraiment supprimer la ressource suivante ?<br /><q>%s</q>',
	'Admin delete res warn' => '<strong>ATTENTION !</strong> Supprimer une ressource entraîne la suppression des captures d’écran qui y sont associées !',

	//Administration - captures d'écran
	'Admin add screen' => 'Ajouter une capture d’écran',
	'Admin edit screen' => 'Mettre à jour une capture d’écran',
	'Admin delete screen' => 'Supprimer une capture d’écran',

	'Admin legend english' => 'Légende en anglais',
	'Admin legend french' => 'Légende en français',
	'Admin download link' => 'Lien de téléchargement',
	'Admin resource screenshots' => 'Captures d’écran',

	'Admin screenshot added redirect' => 'Capture d’écran ajoutée. Redirection …',
	'Admin screenshot updated redirect' => 'Capture mise à jour. Redirection …',
	'Admin screenshot deleted redirect' => 'Capture supprimée. Redirection …',
	'Admin default screen changed redirect' => 'Capture par défaut changée. Redirection …',

	'Admin delete screen head' => 'Supprimer la capture d’écran',
	'Admin confirm delete screen subhead' => 'Confirmer la suppression de la capture d’écran',
	'Admin confirm delete screen info' => 'Souhaitez-vous vraiment supprimer la capture d’écran suivante ?<br /><q>%s</q>',
	'Admin delete screen warn' => '<strong>ATTENTION !</strong> La suppression sera irréversible !',

	//Administration - Types de tutoriels
	'Admin add type' => 'Ajouter un type de tutoriel',
	'Admin edit type' => 'Modifier un type de tutoriel',
	'Admin delete type' => 'Supprimer un type de tutoriel',

	'Admin type name' => 'Nom du type de tutoriel',

	'Admin type added redirect' => 'Type de tutoriel ajoutée. Redirection …',
	'Admin type edited redirect' => 'Type de tutoriel modifiée. Redirection …',
	'Admin type deleted redirect' => 'Type de tutoriel supprimée. Redirection …',

	'Admin delete type head' => 'Supprimer le type de tutoriel',
	'Admin confirm delete type subhead' => 'Confirmer la suppression du type de tutoriel',
	'Admin confirm delete type info' => 'Souhaitez-vous vraiment supprimer le type de tutoriel suivant ?<br /><q>%s</q>',
	'Admin delete type warn' => '<strong>ATTENTION !</strong> Tous les tutoriels utilisant ce type n’auront plus de type défini et devront être édités par la suite !',

	//Administrations - Tutoriels
	'Admin add tut' => 'Ajouter un tutoriel',
	'Admin edit tut' => 'Modifier un tutoriel',
	'Admin delete tut' => 'Supprimer un tutoriel',

	'Admin tut name' => 'Nom du tutoriel',
	'Admin tut desc' => 'Description du tutoriel',
//	'Admin tut extra' => 'Informations supplémentaires',
	'Admin tut icon' => 'Icône du tutoriel',
	'Admin tut type' => 'Type de tutoriel',
	'Admin tut level' => 'Niveau de difficulté',

	'Admin tut added redirect' => 'Tutoriel ajouté. Redirection …',
	'Admin tut edited redirect' => 'Tutoriel modifié. Redirection …',
	'Admin tut deleted redirect' => 'Tutoriel supprimé. Redirection …',

	'Admin delete tut head' => 'Supprimer le tutoriel (et ses parties)',
	'Admin confirm delete tut subhead' => 'Confirmer la suppression du tutoriel',
	'Admin confirm delete tut info' => 'Souhaitez-vous vraiment supprimer le tutoriel suivant ?<br /><q>%s</q>',
	'Admin delete tut warn' => '<strong>ATTENTION !</strong> Supprimer le tutoriel va aussi supprimer les parties qui y sont associées !',

	'Admin add part' => 'Ajouter une partie',
	'Admin edit part' => 'Modifier une partie',
	'Admin delete part' => 'Supprimer une partie',

	'Admin part name' => 'Nom de la partie',
	'Admin part text' => 'Texte de la partie',

	'Admin part added redirect' => 'Partie ajoutée. Redirection …',
	'Admin part edited redirect' => 'Partie modifiée. Redirection …',
	'Admin part deleted redirect' => 'Partie supprimée. Redirection …',

	'Admin delete tut part head' => 'Supprimer la partie de tutoriel',
	'Admin confirm delete tut part subhead' => 'Confirmer la suppression de la partie de tutoriel',
	'Admin confirm delete tut part info' => 'Souhaitez-vous vraiment supprimer la partie de tutoriel suivante ?<br /><q>%s</q>',
	'Admin delete tut part warn' => '<strong>ATTENTION !</strong> Cette opération est irréversible !',

	//Administration - Pages
	'Admin add page' => 'Ajouter une page statique',
	'Admin edit page' => 'Modifier une page statique',
	'Admin delete page' => 'Supprimer une page statique',

	'Admin page title' => 'Titre de la page',
	'Admin page clean title' => 'Titre court de la page',
	'Admin page text' => 'Texte de la page (BBCode autorisé)',

	'Admin page added redirect' => 'Page ajoutée. Redirection …',
	'Admin page edited redirect' => 'Page modifiée. Redirection …',
	'Admin page deleted redirect' => 'Page supprimée. Redirection …',

	'Admin delete page head' => 'Supprimer la page statique',
	'Admin confirm delete page subhead' => 'Confirmer la suppression de la page statique',
	'Admin confirm delete page info' => 'Souhaitez-vous vraiment supprimer la page statique suivante ?<br /><q>%s</q>',
	'Admin delete page warn' => '<strong>ATTENTION !</strong> Cette opération est irréversible !',

	//Erreurs - Public/commun
	'No news' => 'Aucune news',
	'No tutorial' => 'Aucun tutoriel',
	'No style' => 'Aucun style',
	'No screen' => 'Aucune capture d’écran',
	'No cat' => 'Aucune catégorie',
	'No subcat' => 'Aucune sous-catégorie',
	'No resource' => 'Aucune ressource',
	'No comment' => 'Aucun commentaire',
	'No part' => 'Aucune partie',
	'No type' => 'Aucun type',
	'No page' => 'Aucune page',

	'Category not found' => 'La catégorie que vous recherchez n’existe pas !',
	'Subcat not found' => 'La sous-catégorie que vous recherchez n’existe pas !',
	'part not found' => 'La partie que vous recherchez n’existe pas !',
	'Comment not found' => 'Le commentaure que vous recherchez n’existe pas !',
	'Resource not found' => 'La ressource que vous recherchez n’existe pas ou n’est pas validée !',
	'Tutorial not found' => 'Le tutoriel que vous recherchez n’existe pas ou n’est pas validé !',
	'Page not found' => 'La page que vous recherchez n’existe pas !',
	'Wrong format' => 'Le format est incorrect ! Veuillez vous référez à la page de documentation pour savoir comment formater correctement les données',

	'No screenshot sent'	=> 'Aucune capture n’a été envoyée !',
	'Cannot edit comment' => 'Désolé, mais vous n’avez pas les permissions pour modifier ce commentaire !',
	'All caps message' => 'Il n’est pas autorisé d’écrire un message entièrement en lettres capitales.',
	'No message after censoring' => 'Vous devez entrer un message. Après application de la censure, votre message était vide.',
	'Must login to comment' => 'Vous devez vous identifier pour publier un commentaire.',

	'Bad request' => 'Erreur. Le lien que vous avez suivi est incorrect ou périmé.',
	'No view' => 'Vous n\'êtes pas autorisé(e) à visiter ces forums.',
	'No permission'	=> 'Vous n\'êtes pas autorisé(e) à afficher cette page.',
	'Bad referrer' => 'Mauvais HTTP_REFERER. Vous avez été renvoyé(e) vers cette page par une source inconnue ou interdite. Si le problème persiste, assurez-vous que le champ «&#160;URL de base&#160;» de la page Administration&#160;» Options est correctement renseigné et que vous vous rendez sur ces forums en utilisant cette URL. Vous pourrez trouver davantage d\'informations dans la documentation de FluxBB.',

	//Erreurs - Admin
	'Admin no catname' => 'Le nom de la catégorie est vide',
	'Admin no catclear' => 'Le nom raccourci de la catégerie est vide',
	'Admin no data' => 'Aucune donnée n’a été envoyée.  Assurez-vous d’avoir sélectionné les langues à utiliser et rempli les champs correspondants.',
	'Admin no pic' => 'Aucune image n’a été envoyée ou elle ne s’est pas envoyée correctement.',
	'Admin no subname' => 'Le nom de la sous-catégorie est vide',
	'Admin no subclear' => 'Le nom raccourci de la sous-catégorie est vide',
	'Admin no desc' => 'La description est vide',
	'Admin no type' => 'Aucun type n’a été défini',
	'Admin no file' => 'Aucun fichier !',
	'Admin no folder' => 'Le dossier suivant n’existe pas : %s',
	'Admin no resname' => 'Le nom de la ressource envoyée est vide',
	'Admin no shortdesc' => 'La description courte est vide',
	'Admin no longdesc' => 'La description longue est vide',
	'Admin no notes' => 'Les notes de l’auteur sont vides',
	'Admin no typename' => 'Au moins un des deux champs de nom du type de tutoriel n’est pas rempli !',
//	'Admin no typecat' => 'Vous n’avez spécifié aucune catégorie pour le type de tutoriel !',
	'Admin no tutname' => 'Le nom de tutoriel est vide !',
	'Admin no part name' => 'Le nom de la partie est vide !',
	'Admin no text' => 'Le texte est vide !',
	'Admin no language' => 'Aucune langue n’a été cochée !',
	'Admin no page title' => 'Le titre de la page est vide !',
	'Admin no clean title' => 'Le titre court est vide !',

	'Admin must have categories' => 'Vous devez avoir créé des catégories avant d’utiliser cette page !',
	'Admin must be integer'	=>	'La position doit être indiquée sous forme de nombre entier positif.',
	'Admin bad transfer' => 'Une erreur est survenue lors du transfert de l’image',
	'Admin file too big' => 'Le fichier est trop gros !',
	'Admin bad extension' => 'Extension incorrecte !',
	'Admin transfer success' => 'Transfert réussi !',
	'Admin bad chmod' => 'Le CHMOD du dossier demandé ne permet pas l’écriture !  Celui-ci doit être réglé à 777.',
	'Admin upload failed' => 'L’envoi a échoué car au moins un critère n’est pas rempli :',
	'Admin error while uploading' => 'Veuillez corriger les erreurs suivantes avant de reprendre l’envoi :',

	//Bouts de titres spécifiques aux pages v6
	'Pagename home' => 'Accueil',
	'Pagename news' => 'Actualités',
	'Pagename res for' => 'Ressources pour ',
	'Pagename res home' => 'Accueil des ressources',
	'Pagename for' => ' pour ',
	'Pagename tut home' => 'Accueil des tutoriels',
	'Pagename view tutorial' => 'Lire le tutoriel',
	'Pagename view comments' => 'Lire les commentaires',
	'Pagename write comment' => 'Écrire/Modifier un commentaire',
	'Pagename adm home' => 'Accueil de l’administration',
	'Pagename adm cfg' => 'Configuration du site',
	'Pagename adm resources' => 'Administration des ressources',
	'Pagename adm res cat' => 'Administration des catégories de ressources',
	'Pagename adm add res' => 'Ajouter une ressource',
	'Pagename adm tutorials' => 'Administration des tutoriels',
	'Pagename adm tuts cat' => 'Administration des catégories de tutoriels',
	'Pagename adm tuts types' => 'Administration des types de tutoriels',
	'Pagename adm pages' => 'Administration des pages',
	'Pagename adm comments' => 'Administration des commentaires',

	//titres d'accueil
	'Title home' => 'Bienvenue sur %s !',
	'Title news' => 'À la une !',
	'Title resources' => 'Ressources pour vos sites',
	'Title tutorials' => 'Tutoriels pour vos sites',
	'Explain home' => '<p>Des tutoriels et ressources pour vos sites, dans l’esprit du libre !</p>',
	'Explain news' => '<p>Les actualités du site !</p>',
	'Explain res home' => '<p>Vous retrouverez ici les styles, des hacks (modifications, add-ons et snippets) et autres ressources pour personnaliser vos sites et forums</p>',
	'Explain tuts home' => '<p>Vous retrouverez ici les tutoriels et astuces pour vous aider à personnaliser vos sites et forums.</p>',
	'Title adm home' => 'Accueil de l’administration',
	'Explain adm home' => '<p>Ici vous pouvez gérer les ressources, tutoriels, commentaires et pages publiées par vous ou vos membres, ainsi que configurer votre site.</p>',
	'Title adm cfg' => 'Configuration du site',
	'Explain adm cfg' => '<p>C’est à partir d’ici que vous pouvez configurer les modules de votre site.  Notez qu’une notation spéciale est utilisée pour assurer une gestion souple du bilinguisme.  Pour en apprendre plus sur son fonctionnement, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki consacrée à ce système sur le dépôt GitHub du site</a>.</p>',
	'Title adm resources' => 'Administration des ressources',
	'Explain adm res home' => '<p>Ici vous pouvez gérer tout ce qui est relatif aux ressources.</p>',
	'Title adm res cat' => 'Administration des catégories des ressources',
	'Explain adm res cat' => '<p>C’est ici que vous créez, modifiez, supprimez et organisez vos catégories et sous-catégories pour les ressources à publier sur le site.</p><p>Les catégories doivent représenter la plate-forme ou le CMS correspondant aux ressources à publier, tandis que les sous-catégories, permettent de subdiviser les ressources en deux types au sein de la catégorie, selon s’il s’agit d’une modification (hack) ou d’un style.</p>',
	'Explain adm resources' => '<p>Ici vous pouvez ajouter, mettre à jour et supprimer des ressources, ainsi que les captures d’écran associés.</p>',
	'Title adm tutorials' => 'Administration des tutoriels',
	'Explain adm tuts home' => '<p>Ici vous pouvez gérer tout ce qui est relatif aux tutoriels.</p>',
	'Explain adm tutorials' => '<p>Ici vous pouvez ajouter, modifier et supprimer des tutoriels et leurs parties.</p>',
	'Title adm tuts cat' => 'Administration des catégories de tutoriels',
	'Explain adm tuts cat' => '<p>C’est ici que vous créez, modifiez, supprimez et organisez vos catégories pour les tutoriels à publier sur le site.</p><p>Les catégories doivent représenter la plate-forme ou le CMS correspondant aux tutoriels à publier.</p>',
	'Title adm tuts types' => 'Administration des types de tutoriels',
	'Explain adm tuts types' => '<p>Ici vous pouvez gérer les types de tutorials, pour classifier ceux-ci pour faciliter la recherche pour les utilisateurs.  Ainsi par exemple pour des tutoriels Gimp, on peut faire des types « Design », « Retouche », « Astuce », et ainsi de suite.  Certains types plus généraux comme « Astuces » peuvent être utilisés par plus d’une catégorie.</p>',
	'Explain add comment' => '<p>Les commentaires sont faits pour exprimer votre avis sur le tutoriel.  Si des choses sont à améliorer, soyez constructifs dans vos critiques, en expliquant les détails du point à améliorer.<br />IMPORTANT : Les commentaires ne sont pas faits pour les demandes de supports, ceux-ci doivent être faits sur le forum !</p>',
	'Title adm pages' => 'Administration des pages',
	'Explain adm pages' => '<p>Ici vous pouvez créer, modifier et supprimer les pages statiques pour afficher des informations qui seront peu enclins à des changements fréquents.  Les BBCodes sont autorisés.</p>',
	'Title adm comments' => 'Administration des commentaires',
	'Explain adm comments' => '<p>Ici vous pouvez modérer les commentaires, peu importe le tutoriel auquel les commentaires sont rattachés.  Vous pouvez utiliser le menu déroulant pour n’afficher les commentaires d’un tutoriel spécifique.</p>',
	'Explain adm add cat' => '<p>Remplissez tous les champs pour créer une nouvelle catégorie.  Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm edit cat' => '<p>Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm add subcat' => '<p>Remplissez tous les champs pour créer une nouvelle sous-catégorie.  Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm edit subcat' => '<p>Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm add version' => '<p>Remplissez tous les champs pour créer une nouvelle version.</p>',
	'Explain adm add type' => '<p>Remplissez tous les champs pour créer un nouveau type de tutoriel.  Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm edit type' => '<p>Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm add res' => '<p>Remplissez tous les champs pour créer une nouvelle ressource.  Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm edit res' => '<p>Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm add tut' => '<p>Remplissez tous les champs pour créer un nouveau tutoriel.</p><p><strong>IMPORTANT :</strong> Ne mettez pas la totalité du tutoriel dans le champs de description ! Après création du tutoriel, vous pourrez y ajouter des parties, qui sont faites exprès pour ça et qui permettent de diviser votre tutoriel en parties !</p>',
	'Explain adm edit screen' => '<p>Notez que la plupart des champs texte utilisent un système de balisage spécial. Pour apprendre à l’utiliser, consultez <a href="https://github.com/MissGeek/Ishimaru-Design/wiki/Syst%C3%A8me-de-balisage-:-Guide-d%27utilisation">la page wiki sur le dépôt GitHub d’Ishimaru Design</a>.</p>',
	'Explain adm add page' => '<p>Remplissez tous les champs pour créer une nouvelle page statique.  Vous pouvez utiliser le BBCode et les émoticônes, comme si vous étiez en train de poster sur le forum.</p>',
	'Explain adm add part' => '<p>Remplissez tous les champs pour créer une nouvelle partie de tutoriel.  Vous pouvez utiliser du BBCode et des émoticônes pour la mise en forme de votre texte.</p>',
	'Explain adm edit part' => '<p>Vous pouvez utiliser du BBCode et des émoticônes pour la mise en forme de votre texte.</p>'
);









